FROM alpine:3.19
RUN apk add --no-cache \
    openssh python3 sudo bash iproute2 iptables \
    procps net-tools audit shadow findutils grep
RUN echo 'root:changeme' | chpasswd
RUN ssh-keygen -A
RUN sed -i 's/#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config \
    && sed -i 's/#PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config \
    && echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config
EXPOSE 22
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
CMD ["/entrypoint.sh"]
